src/Api/Controllers/CategoryController.cs
using Application.Interfaces.IServices;
using Domain.Entities;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Api.Controllers;

[Authorize]
public class CategoryController : Controller
{
    private readonly ICategoryService _categoryService;
    private readonly IMainCategoryService _mainCategoryService;
    private readonly IOperationService _operationService;

    public CategoryController(ICategoryService categoryService,
        IMainCategoryService mainCategoryService, IOperationService operationService)
    {
        _categoryService = categoryService;
        _mainCategoryService = mainCategoryService;
        _operationService = operationService;
    }

    public async Task<IActionResult> Index()
    {
        var categories = await _categoryService.GetAllCategoriesAsync();

        return View(categories);
    }

    public async Task<IActionResult> Details(int id)
    {
        var category = await _categoryService.GetCategoryByIdAsync(id);
        var mainCategory = await _mainCategoryService.GetMainCategoryByIdAsync(category.MainCategoryId);

        ViewBag.MainCategory = mainCategory.Name;

        return View(category);
    }

    public async Task<IActionResult> Create()
    {
        var mainCategories = await _mainCategoryService.GetAllMainCategoriesFromCurrentYearAsync();
        var categories = await _categoryService.GetAllCategoriesAsync();

        var categoriesList = categories.Select(c => new CustomSelectListItem
        {
            Type = c.Type,
            Name = c.Name,
            Description = c.Description,
            Value = c.Value,
            OneOrMonth = c.OneOrMonth,
            MainCategoryId = c.MainCategoryId
        }).ToList();

        ViewBag.MainCategories = new SelectList(mainCategories, "Id", "Name");
        ViewBag.Categories = categoriesList;

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Category category)
    {
        await _categoryService.CreateCategoryAsync(category);

        return Redirect("/Home/BudgetPlan");
    }

    public async Task<IActionResult> Edit(int id)
    {
        var mainCategories = await _mainCategoryService.GetAllMainCategoriesAsync();
        var category = await _categoryService.GetCategoryByIdAsync(id);

        ViewBag.MainCategories = new SelectList(mainCategories, "Id", "Name");

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Category category)
    {
        await _categoryService.EditCategoryAsync(category);

        return Redirect("/Home/BudgetPlan");
    }

    public async Task<IActionResult> Delete(int id)
    {
        var category = await _categoryService.GetCategoryByIdAsync(id);
        var mainCategory = await _mainCategoryService.GetMainCategoryByIdAsync(category.MainCategoryId);

        ViewBag.MainCategory = mainCategory.Name;

        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(Category category)
    {
        var operations = await _operationService.GetAllOperationsAsync();
        operations = operations.Where(o => o.CategoryId == category.Id).ToList();

        foreach (var operation in operations)
        {
            await _operationService.DeleteOperationAsync(operation);
        }

        await _categoryService.DeleteCategoryAsync(category);

        return Redirect("/Home/BudgetPlan");
    }

    [HttpGet]
    public async Task<IActionResult> GetFilteredCategoriesByOperations(int categoryId, int month, int year, int operationType)
    {
        var categories = await _categoryService.GetAllFilteredCategoriesByOperations(categoryId, month, year, operationType);

        return Json(categories);
    }
}

src/Api/Controllers/HomeController.cs
using Application.Interfaces.IServices;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Api.Controllers;

public class HomeController : Controller
{
    private readonly IMainCategoryService _mainCategoryService;
    private readonly IOperationService _operationService;
    private readonly IBudgetService _budgetService;
    private readonly ICategoryService _categoryService;

    public HomeController(IMainCategoryService mainCategoryRepository, IOperationService operationService,
        IBudgetService budgetService, ICategoryService categoryService)
    {
        _mainCategoryService = mainCategoryRepository;
        _operationService = operationService;
        _budgetService = budgetService;
        _categoryService = categoryService;
    }

    public async Task<IActionResult> Index(int year)
    {
        var operations = await _operationService.GetLastTenOperations();
        var categories = await _categoryService.GetAllCategoriesAsync();
        var budgetPlan = _budgetService.BudgetPlan(year);

        if (User.Identity!.IsAuthenticated)
        {
            ViewBag.BudgetPlan = budgetPlan;
            ViewBag.CategoriesArray = categories;
            return View(operations);
        }
        else
        {
            return View("HomePage");
        }
    }

    [Authorize]
    public async Task<IActionResult> BudgetPlan(int year)
    {
        var budgetPlan = _budgetService.BudgetPlan(year);
        var filteredYears = await _mainCategoryService.GetFilteredMainCategoriesYearsAsync();

        ViewBag.Years = new SelectList(filteredYears);

        return View(budgetPlan);
    }

    [Authorize]
    public async Task<IActionResult> BudgetStatus(int year, int month)
    {
        var budgetStatus = _budgetService.BudgetStatus(year, month);
        var filteredYears = await _operationService.GetFilteredOperationsYearsAsync();

        ViewBag.Years = new SelectList(filteredYears);

        return View(budgetStatus);
    }

    [Authorize]
    public IActionResult BudgetPlanData(int year)
    {
        var budgetPlan = _budgetService.BudgetPlan(year);

        return Json(budgetPlan);
    }

    public IActionResult Rules()
    {
        return View("Rules");
    }

    public IActionResult More()
    {
        return View("More");
    }

    public IActionResult HowTo()
    {
        return View("HowTo");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Api/Controllers/MainCategoryController.cs
using Application.Interfaces.IServices;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers;

[Authorize]
public class MainCategoryController : Controller
{
    private readonly IMainCategoryService _mainCategoryService;

    public MainCategoryController(IMainCategoryService mainCategoryService)
    {
        _mainCategoryService = mainCategoryService;
    }

    public async Task<IActionResult> Index()
    {
        var mainCategories = await _mainCategoryService.GetAllMainCategoriesAsync();

        return View(mainCategories);
    }

    public async Task<IActionResult> Details(int id)
    {
        var mainCategory = await _mainCategoryService.GetMainCategoryByIdAsync(id);

        return View(mainCategory);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(MainCategory mainCategory)
    {
        await _mainCategoryService.CreateMainCategoryAsync(mainCategory);

        return Redirect("/Home/BudgetPlan");
    }

    public async Task<IActionResult> Edit(int id)
    {
        var mainCategory = await _mainCategoryService.GetMainCategoryByIdAsync(id);

        return View(mainCategory);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(MainCategory mainCategory)
    {
        await _mainCategoryService.EditMainCategoryAsync(mainCategory);

        return Redirect("/Home/BudgetPlan");
    }

    public async Task<IActionResult> Delete(int id)
    {
        var mainCategory = await _mainCategoryService.GetMainCategoryByIdAsync(id);

        return View(mainCategory);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(MainCategory mainCategory)
    {
        await _mainCategoryService.DeleteMainCategoryAsync(mainCategory);

        return Redirect("/Home/BudgetPlan");
    }
}

src/Api/Controllers/OperationController.cs
using Application.Interfaces.IServices;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Api.Controllers;

[Authorize]
public class OperationController : Controller
{
    private readonly IOperationService _operationService;
    private readonly ICategoryService _categoryService;
    private readonly IAccountService _accountService;

    public OperationController(IOperationService operationService, ICategoryService categoryService,
        IAccountService accountService)
    {
        _operationService = operationService;
        _categoryService = categoryService;
        _accountService = accountService;
    }

    public async Task<IActionResult> Index(int categoryId, int month, int year, int? page, int? pageSize)
    {
        var operations = await _operationService.GetFilteredOperationsByCategoryIdMonthYearAsync(categoryId, month, year);
        var filteredYears = await _operationService.GetFilteredOperationsYearsAsync();
        var categories = await _categoryService.GetAllCategoriesAsync();
        var expenses = await _operationService.GetOperationDataTypeSum(operations, 0);
        var incomes = await _operationService.GetOperationDataTypeSum(operations, 1);
        var pagedOperations = _operationService.PagedOperations(operations, page, pageSize, out int totalItemCount);

        ViewData["categoryId"] = categoryId;
        ViewData["month"] = month;
        ViewData["year"] = year;

        ViewBag.TotalItemCount = totalItemCount;
        ViewBag.Years = new SelectList(filteredYears);
        ViewBag.Categories = new SelectList(categories, "Id", "Name");
        ViewBag.CategoriesArray = categories;
        ViewBag.Spends = expenses;
        ViewBag.Incomes = incomes;

        return View(pagedOperations);
    }

    public async Task<IActionResult> Details(int id)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);
        var category = await _categoryService.GetCategoryByIdAsync(operation.CategoryId);
        var account = await _accountService.GetAccountByIdAsync(operation.BudgetId);

        ViewBag.Category = category.Name;
        ViewBag.Account = account.Name;

        return View(operation);
    }

    public async Task<IActionResult> CreateSpend()
    {
        var accounts = await _accountService.GetAllAccountsAsync();
        var categories = await _categoryService.GetAllCategoriesByTypeAsync(0);

        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");
        ViewBag.Categories = new SelectList(categories, "Id", "Name");

        return View();
    }

    public async Task<IActionResult> CreateIncome()
    {
        var accounts = await _accountService.GetAllAccountsAsync();
        var categories = await _categoryService.GetAllCategoriesByTypeAsync(1);

        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");
        ViewBag.Categories = new SelectList(categories, "Id", "Name");

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Operation operation)
    {
        await _operationService.CreateOperationAsync(operation);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Edit(int id)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);
        var categories = await _categoryService.GetAllCategoriesAsync();
        var accounts = await _accountService.GetAllAccountsAsync();

        ViewBag.Categories = new SelectList(categories, "Id", "Name");
        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");

        return View(operation);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Operation actualOperation)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);

        await _operationService.EditOperationAsync(actualOperation, operation);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);
        var category = await _categoryService.GetCategoryByIdAsync(operation.CategoryId);
        var account = await _accountService.GetAccountByIdAsync(operation.BudgetId);

        ViewBag.Category = category.Name;
        ViewBag.Account = account.Name;

        return View(operation);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id, Operation operation)
    {
        operation = await _operationService.GetOperationByIdAsync(operation.Id);

        await _operationService.DeleteOperationAsync(operation);

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> GetOperationData(int category, int month, int year, int operationType)
    {
        var operations = await _operationService.GetFilteredOperationsByCategoryIdMonthYearAsync(category, month, year);
        var operationData = await _operationService.GetOperationDataType(operations, operationType);

        return Json(operationData);
    }
}

src/Api/Views/Home/BudgetPlan.cshtml
@using Domain.Models
@model BudgetModel
@{
    ViewData["Title"] = "PLAN BUDŻETU";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="subpage__frame">
    <div class="info__section">
        <div class="text__data text-margin-plan sm-first-plan">
            <h5 class="header__data">
                Zaplanowane wpływy:
            </h5>
            <h4 class="data income mt-3">
                @Model.PlannedIncomes zł
            </h4>
        </div>
        <div class="chart__field sm-fourth-plan">
            <script>
                var Incomes = @Html.Raw(Json.Serialize(@Model.PlannedIncomes));
                var Spends = @Html.Raw(Json.Serialize(@Model.PlannedExpenses));
            </script>
            <canvas id="barChart"></canvas>
        </div>
        <div class="text__data sm-second-plan text-margin-plan">
            <h5 class="header__data">
                Zaplanowane wydatki:
            </h5>
            <h4 class="data spend mt-3">
                @Model.PlannedExpenses zł
            </h4>
        </div>
        <div class="vertical__bar sm-plan-none"></div>
        <div class="text__data text-margin-plan sm-third-plan">
            <h5 class="header__data">
                Niezaplanowane środki:
            </h5>
            <h4 class="data mt-3">
                @(Model.PlannedIncomes - Model.PlannedExpenses) zł
            </h4>
        </div>
    </div>
    <div class="option__section mb-4">
        <div class="operations__button__holder">
            <button type="button" class="option__button extra-spacing" onclick="location.href='@Url.Action("Create", "MainCategory")'">Dodaj kategorię</button>
            <button type="button" class="option__button" onclick="location.href='@Url.Action("Create", "Category")'">Dodaj podkategorię</button>
        </div>
        <div class="filter__button">
            <form asp-controller="Home" asp-action="BudgetPlan" method="get" id="filters" class="option__button filter filter__holder">
                @Html.DropDownList("Year", (SelectList)ViewBag.Years, "Wybierz rok", new { @class = "form-control" })
                <button type="submit" form="filters" class="button__search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                    </svg>
                </button>
            </form>
        </div>
    </div>

    <table class="table table-shadow mt-4">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Miesięcznie</th>
                <th>Rocznie</th>
                <th class="sm-none">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var mainCategory in @Model.MainCategories)
            {
                <tr class="standard__row">
                    <td class="bold one__fourth clickable" onclick="window.location.href = '@Url.Action("Details", "MainCategory", new { id = mainCategory.Id })';">
                        @mainCategory.Name
                    </td>
                    <td class="one__fourth clickable" onclick="window.location.href = '@Url.Action("Details", "MainCategory", new { id = mainCategory.Id })';">
                    </td>
                    <td class="one__fourth clickable" onclick="window.location.href = '@Url.Action("Details", "MainCategory", new { id = mainCategory.Id })';">
                    </td>
                    <td class="one__fourth sm-none">
                        <div class="dropdown">
                            <button class="options__button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                                    <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" />
                                </svg>
                            </button>
                            <div class="dropdown-menu dropdown__bootstrap__options" aria-labelledby="dropdownMenuButton">
                                <a asp-action="Edit" asp-controller="MainCategory" class="text-white submenu__text border-0" asp-route-id="@mainCategory.Id">Edytuj</a>
                                <a asp-action="Details" asp-controller="MainCategory" class="text-white submenu__text border-0" asp-route-id="@mainCategory.Id">Szczegóły</a>
                                <a asp-action="Delete" asp-controller="MainCategory" class="text-white submenu__text border-0" asp-route-id="@mainCategory.Id">Usuń</a>
                            </div>
                        </div>
                    </td>
                </tr>
                @foreach (var category in Model.Categories)
                {
                    @if (mainCategory.Id == category.MainCategoryId)
                    {
                        <tr class="standard__row clickable">
                            <td class="one__fourth" onclick="window.location.href = '@Url.Action("Details", "Category", new { id = category.Id })';">
                                @category.Name
                            </td>
                            <td class="one__fourth clickable" onclick="window.location.href = '@Url.Action("Details", "Category", new { id = category.Id })';">
                                @if (category.Type == 0)
                                {
                                    <span class="spend">@category.Value zł</span>
                                }
                                else
                                {
                                    <span class="income">@category.Value zł</span>

                                }
                            </td>
                            <td class="one__fourth clickable" onclick="window.location.href = '@Url.Action("Details", "Category", new { id = category.Id })';">
                                @if (category.OneOrMonth == true)
                                {
                                    @if (category.Type == 0)
                                    {
                                        <span class="spend">@(category.Value * (13 - DateTime.Now.Month)) zł</span>
                                    }
                                    else
                                    {
                                        <span class="income">@(category.Value * (13 - DateTime.Now.Month)) zł</span>

                                    }
                                }
                                else
                                {
                                    @if (category.Type == 0)
                                    {
                                        <span class="spend">@category.Value zł</span>
                                    }
                                    else
                                    {
                                        <span class="income">@category.Value zł</span>

                                    }
                                }
                            </td>
                            <td class="options sm-none">
                                <div class="dropdown">
                                    <button class="options__button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                                            <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" />
                                        </svg>
                                    </button>
                                    <div class="dropdown-menu dropdown__bootstrap__options" aria-labelledby="dropdownMenuButton">
                                        <a asp-action="Edit" asp-controller="Category" class="text-white submenu__text border-0" asp-route-id="@category.Id">Edytuj</a>
                                        <a asp-action="Details" asp-controller="Category" class="text-white submenu__text border-0" asp-route-id="@category.Id">Szczegóły</a>
                                        <a asp-action="Delete" asp-controller="Category" class="text-white submenu__text border-0" asp-route-id="@category.Id">Usuń</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>

<script src="~/js/Home/barChart.js" asp-append-version="true"></script>

src/Api/Views/Home/Index.cshtml
@using Domain.Models
@{
	ViewData["Title"] = "PANEL GŁÓWNY";
	var budgetPlan = ViewBag.BudgetPlan as BudgetModel;
}
@model IEnumerable<Operation>


<div class="subpage__frame">
	<div class="info__section__main__panel">
		<div class="chart__field__bar__main__panel__left">
			<canvas class="chart" id="combinedChart"></canvas>
			<div class="chart__text">Struktura wydatków</div>
		</div>
		<div class="chart__field__bar__main__panel__center">
			<canvas class="lineChart" id="yearStructureChart"></canvas>
		</div>
		<div class="chart__field__bar__main__panel__right">
			<canvas class="chart" id="incomesChart"></canvas>
			<div class="chart__text">Realizacja budżetu</div>
		</div>
	</div>
	<div class="main__panel__half mt-4">
		<div class="small__frame">
			<div class="half__holder">
				<h5 class="small__header__button">
					Ostatnie operacje
				</h5>
				<div>
					<a asp-controller="Operation" asp-action="Index" class="more__button text-light">Wszystkie operacje</a>
				</div>
			</div>
			<table class="table table-shadow mt-4">
				<thead>
					<tr>
						<th>Nazwa</th>
						<th class="centrum__cell">Data</th>
						<th class="last__cell">Kwota</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr class="standard__row">
							<td class="one__fourth clickable" onclick="window.location.href = '@Url.Action("Details", "Operation", new { id = item.Id })';">
								@foreach (var category in ViewBag.CategoriesArray)
								{
									if (item.CategoryId == category.Id)
									{
										@category.Name
									}
								}
							<td class="one__third clickable centrum__cell" onclick="window.location.href = '@Url.Action("Details", "Operation", new { id = item.Id })';">
									@((item.CreateDate).ToString("dd.MM.yyyy"))
							</td>
							@if (item.Type == 0)
							{
								<td class="one__third spend clickable last__cell" onclick="window.location.href = '@Url.Action("Details", "Operation", new { id = item.Id })';">
									@Html.DisplayFor(modelItem => item.Value) zł
								</td>
							}
							else
							{
								<td class="one__third income clickable last__cell" onclick="window.location.href = '@Url.Action("Details", "Operation", new { id = item.Id })';">
									@Html.DisplayFor(modelItem => item.Value) zł
								</td>
							}
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
	<div class="main__panel__half mt-4">
		<h5 class="small__header margin-left2">
			Realizacja zaplanowanego budżetu
		</h5>
		<div class="border__nav">
			<div class="info__section__main__panel">
				<div class="chart__field">
					<canvas id="summaryOperations"></canvas>
				</div>
			</div>
			<h5 class="small__header margin-left2 mt-4">
				Oszczędności wynikajace z planu budżetu
			</h5>
			<div id="chartContainer" class="info__section__main__panel">
				<div class="chart__field">
					<canvas id="summaryBarChart"></canvas>
				</div>
				<script>
					var Incomes = @Html.Raw(Json.Serialize(@budgetPlan!.PlannedIncomes));
					var Spends = @Html.Raw(Json.Serialize(@budgetPlan!.PlannedExpenses));
				</script>
				<div class="chart__field">
					<canvas id="barChart"></canvas>
				</div>
				<div class="text__data m-4">
					<h4 class="data mt-3">
						@(@budgetPlan.PlannedIncomes - @budgetPlan.PlannedExpenses) zł
					</h4>
				</div>
			</div>

		</div>
	</div>
</div>

<script src="~/js/display.js" asp-append-version="true"></script>
<script src="~/js/randomChartColors.js" asp-append-version="true"></script>
<script src="~/js/Operations/incomesAndExpensesFetchData.js" asp-append-version="true"></script>
<script src="~/js/Operations/incomesChart.js" asp-append-version="true"></script>
<script src="~/js/Home/barChart.js" asp-append-version="true"></script>
<script src="~/js/Home/summaryOperationsChartFetchData.js" asp-append-version="true"></script>
<script src="~/js/Home/summaryOperationsChart.js" asp-append-version="true"></script>
<script src="~/js/Accounts/combinedChartFetchData.js" asp-append-version="true"></script>
<script src="~/js/Accounts/combinedChart.js" asp-append-version="true"></script>
<script src="~/js/Home/yearStructureChartFetchData.js" asp-append-version="true"></script>
<script src="~/js/Home/yearStructureChart.js" asp-append-version="true"></script>