src/Api/Controllers/OperationController.cs
using Application.Interfaces.IServices;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Api.Controllers;

[Authorize]
public class OperationController : Controller
{
    private readonly IOperationService _operationService;
    private readonly ICategoryService _categoryService;
    private readonly IAccountService _accountService;

    public OperationController(IOperationService operationService, ICategoryService categoryService,
        IAccountService accountService)
    {
        _operationService = operationService;
        _categoryService = categoryService;
        _accountService = accountService;
    }

    public async Task<IActionResult> Index(int categoryId, int month, int year, int? page, int? pageSize)
    {
        var operations = await _operationService.GetFilteredOperationsByCategoryIdMonthYearAsync(categoryId, month, year);
        var filteredYears = await _operationService.GetFilteredOperationsYearsAsync();
        var categories = await _categoryService.GetAllCategoriesAsync();
        var expenses = await _operationService.GetOperationDataTypeSum(operations, 0);
        var incomes = await _operationService.GetOperationDataTypeSum(operations, 1);
        var pagedOperations = _operationService.PagedOperations(operations, page, pageSize, out int totalItemCount);

        ViewData["categoryId"] = categoryId;
        ViewData["month"] = month;
        ViewData["year"] = year;

        ViewBag.TotalItemCount = totalItemCount;
        ViewBag.Years = new SelectList(filteredYears);
        ViewBag.Categories = new SelectList(categories, "Id", "Name");
        ViewBag.CategoriesArray = categories;
        ViewBag.Spends = expenses;
        ViewBag.Incomes = incomes;

        return View(pagedOperations);
    }

    public async Task<IActionResult> Details(int id)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);
        var category = await _categoryService.GetCategoryByIdAsync(operation.CategoryId);
        var account = await _accountService.GetAccountByIdAsync(operation.BudgetId);

        ViewBag.Category = category.Name;
        ViewBag.Account = account.Name;

        return View(operation);
    }

    public async Task<IActionResult> CreateSpend()
    {
        var accounts = await _accountService.GetAllAccountsAsync();
        var categories = await _categoryService.GetAllCategoriesByTypeAsync(0);

        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");
        ViewBag.Categories = new SelectList(categories, "Id", "Name");

        return View();
    }

    public async Task<IActionResult> CreateIncome()
    {
        var accounts = await _accountService.GetAllAccountsAsync();
        var categories = await _categoryService.GetAllCategoriesByTypeAsync(1);

        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");
        ViewBag.Categories = new SelectList(categories, "Id", "Name");

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Operation operation)
    {
        await _operationService.CreateOperationAsync(operation);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Edit(int id)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);
        var categories = await _categoryService.GetAllCategoriesAsync();
        var accounts = await _accountService.GetAllAccountsAsync();

        ViewBag.Categories = new SelectList(categories, "Id", "Name");
        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");

        return View(operation);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Operation actualOperation)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);

        await _operationService.EditOperationAsync(actualOperation, operation);

        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var operation = await _operationService.GetOperationByIdAsync(id);
        var category = await _categoryService.GetCategoryByIdAsync(operation.CategoryId);
        var account = await _accountService.GetAccountByIdAsync(operation.BudgetId);

        ViewBag.Category = category.Name;
        ViewBag.Account = account.Name;

        return View(operation);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id, Operation operation)
    {
        operation = await _operationService.GetOperationByIdAsync(operation.Id);

        await _operationService.DeleteOperationAsync(operation);

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public async Task<IActionResult> GetOperationData(int category, int month, int year, int operationType)
    {
        var operations = await _operationService.GetFilteredOperationsByCategoryIdMonthYearAsync(category, month, year);
        var operationData = await _operationService.GetOperationDataType(operations, operationType);

        return Json(operationData);
    }
}

src/Api/Controllers/SavingsController.cs
using Application.Interfaces.IServices;
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Api.Controllers;

[Authorize]
public class SavingsController : Controller
{
    private readonly IAccountService _accountService;
    private readonly ISavingService _savingService;

    public SavingsController(IAccountService accountService, ISavingService savingService)
    {
        _savingService = savingService;
        _accountService = accountService;
    }

    public async Task<ActionResult> Index()
    {
        var savings = await _savingService.GetAllSavingsAsync();

        return View(savings);
    }

    public async Task<ActionResult> Details(int id)
    {
        var saving = await _savingService.GetSavingByIdAsync(id);

        return View(saving);
    }

    public async Task<ActionResult> CreateAsync()
    {
        var accounts = await _accountService.GetAllAccountsAsync();
        ViewBag.Accounts = new SelectList(accounts, "Id", "Name");

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Create(Saving saving)
    {
        await _savingService.CreateSavingAsync(saving);

        return RedirectToAction(nameof(Index));
    }

    public async Task<ActionResult> Edit(int id)
    {
        var saving = await _savingService.GetSavingByIdAsync(id);

        return View(saving);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, decimal value, decimal aimValue)
    {
        await _savingService.EditSavingAsync(id, value, aimValue);
        return RedirectToAction(nameof(Index));
    }

    public async Task<ActionResult> Delete(int id)
    {
        var saving = await _savingService.GetSavingByIdAsync(id);

        return View(saving);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Delete(Saving saving, int id)
    {
        await _savingService.DeleteSavingAsync(id);

        return RedirectToAction(nameof(Index));
    }

    public async Task<ActionResult> Supply(int id)
    {
        var saving = await _savingService.GetSavingByIdAsync(id);

        return View(saving);
    }

    [HttpPost]
    public async Task<IActionResult> SavingSupplyMoney(IFormCollection form, decimal value)
    {
        await _savingService.SavingSupplyMoney(form, value);
        return Redirect("/Savings");
    }
}

src/Api/Views/Shared/_Dropdown_Menu.cshtml
<div class="pos-f-t w-100 none menu-background">
    <nav class="navbar navbar-dark nav-blue w-100">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-light logo__holder__home m-left">
            <div class="icon__holder__home">
                <img class="logo__dropdown" src="/logoBM.png" alt="Budget plan icon">
            </div>
        </a>
        <button class="navbar-toggler m-right" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="collapse collapse-blue" id="navbarToggleExternalContent">
        <div class="w-100">
            <partial name="_LoginPartialWhite" />
        </div>
    </div>
</div>

src/Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BudgetManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <partial name="_LoggedMenu" />
    <div class="space"></div>
    <div class="left__container">
            <div class="logo__holder">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-light">
                <div class="icon__holder">
                    <img class="logo__icon" src="/logoBM.png" alt="Budget plan icon">
                </div>
            </a>
            </div>

        @if (User.Identity!.IsAuthenticated)
        {          
            <div id="authenticated" class="left__menu">
                    <ul class="menu navbar-nav flex-grow-1">
                        <li class="nav-item menu__button">
                            <a asp-area="" asp-controller="Operation" asp-action="Index" class="nav-link text-light">
                                <div class="icon__holder">
                                    <img class="menu__icon" src="/Operations.PNG" alt="Budget plan icon">
                                </div>
                                OPERACJE
                            </a>
                        </li>
                        <li class="nav-item menu__button">
                            <a asp-area="" asp-controller="Account" asp-action="Index" class="nav-link text-light">
                            <div class="icon__holder">
                                <img class="menu__icon" src="/Finances.PNG" alt="Budget plan icon">
                            </div>
                            FINANSE
                            </a>
                        </li>
                        <li class="nav-item menu__button">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="BudgetPlan">
                            <div class="icon__holder">
                                <img class="menu__icon" src="/BudgetPlan.PNG" alt="Budget plan icon">
                            </div>
                            PLAN BUDŻETU
                            </a>
                        </li>
                        <li class="nav-item menu__button">
                            <a class="nav-link text-light" asp-area="" asp-controller="Savings" asp-action="Index">
                            <div class="icon__holder">
                                <img class="menu__icon" src="/Savings.PNG" alt="Budget plan icon">
                            </div>
                            OSZCZĘDNOŚCI
                            </a>
                        </li>
                        <li class="nav-item menu__button">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="BudgetStatus">
                            <div class="icon__holder">
                                <img class="menu__icon" src="/Reports.PNG" alt="Budget plan icon">
                            </div>
                            BILANS ROCZNY
                            </a>
                        </li>
                    </ul>
            </div>
            <div id="authenticated-2" class="rules__menu">
                <ul class="menu navbar-nav flex-grow-1">
                    <li class="nav-item menu__button">
                        <a asp-area="" asp-controller="Home" asp-action="Rules" class="nav-link text-light rules-margin">
                            ZASADY I PRYWATNOŚĆ
                        </a>
                    </li>
                </ul>
            </div>
        }
        </div>
    <div class="right__container">
        <div class="top__section__upper">
            <div class="login__buttons">
                <partial name="_LoginPartial" />
            </div>
        </div>
        <div class="top__section">
            <div>
                <h1>@ViewData["Title"]</h1>
            </div>
        </div>
        <div class="left__bar">

        </div>
        <div class="main__section conatiner__fluid">
            <main role="main" class="pb-3 main__section__frame">
                @RenderBody()
            </main>
        </div>
        <footer class="footer text-muted">
            <div class="footer__text">
                &copy; 2024 - Praca inżynierska WSB Merito w&nbsp;Poznaniu
            </div>
        </footer>
    </div>   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

src/Api/Views/Shared/_Layout_HomePage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BudgetManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Api/Views/Shared/_Layout_login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] BudgetManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Api/Views/Shared/_LoggedMenu.cshtml
<div class="pos-f-t  w-100 none menu-background fixed">
    <nav class="navbar navbar-dark nav-blue w-100">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link text-light logo__holder__home m-left">
            <div class="icon__holder__home">
                <img class="logo__dropdown" src="/logoBM.png" alt="Budget plan icon">
            </div>
        </a>
        <button class="navbar-toggler m-right" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent2" aria-controls="navbarToggleExternalContent2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div class="collapse collapse-blue absolute-menu" id="navbarToggleExternalContent2">
        <div class="dropdown__holder">
            <div class="first__options">
                <a asp-area="" asp-controller="Operation" asp-action="Index" class="nav-link text-light text-center w-100">
                    OPERACJE
                </a>
                <a asp-area="" asp-controller="Account" asp-action="Index" class="nav-link text-light text-center w-100">
                    FINANSE
                </a>
                <a class="nav-link text-light text-center w-100" asp-area="" asp-controller="Home" asp-action="BudgetPlan">
                    PLAN BUDŻETU
                </a>
                <a class="nav-link text-center text-light w-100" asp-area="" asp-controller="Savings" asp-action="Index">
                    OSZCZĘDNOŚCI
                </a>
                <a class="nav-link text-light text-center w-100" asp-area="" asp-controller="Home" asp-action="BudgetStatus">
                    BILANS ROCZNY
                </a>
            </div>
            <div class="second__options">
                <a id="manage2" class="nav-link text-light text-center w-100" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">PANEL UŻYTKOWNIKA</a>
                <form id="logoutForm" class="nav-item login__button" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nav-link login__button text-center no-decorations border-0">WYLOGUJ</button>
                </form>
            </div>
            <div class="third__options">
                <a asp-area="" asp-controller="Home" asp-action="Rules" class="nav-link text-light">
                    ZASADY I PRYWATNOŚĆ
                </a>
            </div>
        </div>
    </div>
</div>

src/Api/Views/Shared/_LoginPartialWhite.cshtml
@using Domain.Models
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUserModel> SignInManager
@inject UserManager<IdentityUserModel> UserManager

<div class="navbar-nav">
	@if (SignInManager.IsSignedIn(User))
	{
		<div id="login__status" class="login__status mt-2">
			<div id="notification" class="nav-item login__button">
				<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill grey" viewBox="0 0 16 16" onclick="showNotifications(this)">
					<path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z" />
				</svg>
				<div id="dot" class="notification-dot"></div>
				<div class="dropdown__container">
					<div id="notificationsContainer" class="dropdown__notifications text-white"></div>
				</div>
			</div>
			<div class="nav-item login__button">
				<a id="manage" class="nav-link text-dark status__text" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@UserManager.GetUserName(User)</a>
				<span class="user__status">Użytkownik</span>
			</div>
			<div class="nav-item center">
				<button id="arrow__down" type="button" class="button" onclick="showMenu(this)">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
						<path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
					</svg>
				</button>
				<div class="dropdown__container">
					<div id="dropdown__menu" class="dropdown__element text-white">
						<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
							<button id="logout" type="submit" class="nav-link btn btn-link submenu__text border-0">Wyloguj</button>
						</form>
					</div>
				</div>
			</div>
		</div>

	}
	else
	{
		<div class="login__status">
			<div class="nav-item login__button margin-right">
				<a class="nav-link text-light" id="register" asp-area="Identity" asp-page="/Account/Register">Rejestracja</a>
			</div>
			<div class="nav-item login__button">
				<a class="nav-link text-light" id="login" asp-area="Identity" asp-page="/Account/Login">Logowanie</a>
			</div>
		</div>

		<div class="login__status__small">
			<div class="nav-item login__button w-100">
				<a class="nav-link text-light" id="register" asp-area="Identity" asp-page="/Account/Register">Rejestracja</a>
			</div>
			<div class="nav-item login__button w-100">
				<a class="nav-link text-light" id="login" asp-area="Identity" asp-page="/Account/Login">Logowanie</a>
			</div>
		</div>
	}
</div>